const userRouter = require('./userRouter');
const sellerRouter = require('./sellerRoutes');
const adminRouter = require('./adminRoutes');
const addressRouter = require('./addressRoutes');
const productRouter = require("./productRoutes");
const brandRoutes = require("./brandRoutes");
const categoryRoutes = require("./categoryRoutes")
const cartRoutes = require("./cartRoutes")
const reviewsRouter = require("./reviewsRoutes")
const orderRouter = require("./orderRoutes")
module.exports = { userRouter, sellerRouter, orderRouter,adminRouter, reviewsRouter,addressRouter ,productRouter,categoryRoutes,brandRoutes,cartRoutes};
