const userRouter = require('./userRouter');
const sellerRouter = require('./sellerRoutes');
const adminRouter = require('./adminRoutes');
const addressRouter = require('./addressRoutes');
const productRouter = require("./productRoutes");
const brandRoutes = require("./brandRoutes");
const categoryRoutes = require("./categoryRoutes")
const cartRoutes = require("./cartRoutes")
module.exports = { userRouter, sellerRouter, adminRouter, addressRouter ,productRouter,categoryRoutes,brandRoutes,cartRoutes};
