const User = require('./userModel');
const userAddress = require('./addressModel');
const sellerProfile = require('./sellerProfile');
const product = require('./productmodel');
const brand = require('./brandmodel');
const category = require('./catagorymodel');
const image = require('./imagemodel');
const cart = require("./cartModel")
const review = require("./reviewModel")
module.exports = {User, userAddress ,sellerProfile,product,brand,category,image,cart,review};
