const User = require('./userModel');
const address = require('./addressModel');
const sellerProfile = require('./sellerProfile');
const product = require('./productmodel');
const brand = require('./brandmodel');
const category = require('./catagorymodel');
const image = require('./imagemodel');
const cart = require("./cartModel")
const review = require("./reviewModel")
const order = require("./orderModel")
module.exports = {User, address ,sellerProfile,product,brand,category,image,cart,review,order};
